### Замена регистра слов на противоположный. Если есть спецсимволы или кодировка не utf-8, выводит *ERROR*.

In [84]:
#1. 
from string import punctuation # А как тут обойтись вообще без доп. библиотек?

entered = str(input('Enter the string: '))


def check_spec_characters(entered):
    check_failed = [letter for letter in punctuation if letter in entered]
    if check_failed:
        return 1
    else:
        return 0


def check_eng_symbols(entered):
    try:
        entered.encode(encoding='utf-8').decode('ascii')
    except UnicodeDecodeError:
        return 1
    else:
        return 0


if ((check_spec_characters(entered) == 0) and (check_eng_symbols(entered) == 0)):
    entered = list(entered)
    concateneted = []
    for letter in entered:
        if letter.isupper():
            letter = letter.lower()
            concateneted.append(str(letter))
        elif letter.islower():
            letter = letter.upper()
            concateneted.append(str(letter))
    concateneted = ''.join(concateneted)
    print(concateneted)
else:
    print('ERROR')

Enter the string: msu
MSU


### Получаем на вход число $N$ и печатаем от 1 до $N^2$ в формате таблички $N*N$.

In [35]:
#2. 
import numpy as np

N = int(input('Enter N: '))

typed = np.arange(1, N*N+1, 1)
typed = typed.reshape(N, N, order='F') # the first index changing fastest, and the last index changing slowest
print(typed)

Enter N: 4
[[ 1  5  9 13]
 [ 2  6 10 14]
 [ 3  7 11 15]
 [ 4  8 12 16]]


### Программа получает на вход числа $x$ и $k$ и выводит сумму $1^k + ... + x^k$.

In [55]:
#3 
x, k = map(int, input().split())

summ = 0
for i in range(1, x+1):
    summ += (i ** k)

print(summ)

8 1
36


### Программа получает на вход предложение на английском языке и заменяет в нём артикли $a$ или $an$ на $the$.

In [110]:
#4 Мне не нравится этот повторяющийся код, но до более изящного решения не додумался. А оно тут есть?

sentence = str(input())
splitted = sentence.split(' ')


# Заменяем слово следующим способом: берем найденный по 'if' элемент в списке и удаляем его. Заместо старого элемента ставим новый.
for every_word in splitted:
    if (every_word == 'a') | (every_word == 'an'):
        place_to_paste = splitted.index(every_word)
        splitted.remove(every_word)
        splitted.insert(place_to_paste, 'the')
        improved = ' '.join(splitted)
        
    elif (every_word.isupper() == True) & ((every_word == 'AN') | (every_word == 'A')):
        place_to_paste = splitted.index(every_word)
        splitted.remove(every_word)
        splitted.insert(place_to_paste, 'THE')
        improved = ' '.join(splitted)
        
    elif (every_word == 'A') | (every_word == 'An'):
        place_to_paste = splitted.index(every_word)
        splitted.remove(every_word)
        splitted.insert(place_to_paste, 'The')
        improved = ' '.join(splitted)

print(improved)
        

Something to drink - a glass of wine
Something to drink - the glass of wine
